# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Update npm
          command: 'pwd  && sudo apt-get update && sudo apt-get install nodejs && sudo apt-get install npm &&  echo  "NPM insalled"  && sudo npm -v && sudo ln -s "$(which nodejs)" /usr/bin/node && sudo node -v'

      - run:
          name: Update node
          command: 'pwd  && sudo npm cache clean -f && sudo npm install -g n && sudo n stable'


      - run:
          name: Update Dependencies
          command: 'pwd &&  npm -v &&  npm install --unsafe-perm  &&  echo "NPM Install Completed" '

      - run:
          name: Install Angular CLI
          command: 'pwd && sudo npm install -g @angular/cli --unsafe-perm  &&  echo "ANGULAR CLI Install Completed"'

      - run:
          name: Install Firebase CLI
          command: 'pwd && sudo npm install -g @angular/cli --unsafe-perm  &&  echo "ANGULAR CLI Install Completed"'

      - run:
          name: Check Angular CLI
          command: 'ng -v'

      # - run: yarn install
      - run:
          name: Build Production
          command: ng build --prod

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test